#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="$ROOT_DIR/00_Documentation/09_Reports/bootstrap"
TIMESTAMP="$(date +%F-%H%M%S)"
REPORT="$REPORT_DIR/${TIMESTAMP}-bootstrap-report.md"

mkdir -p "$REPORT_DIR"
cd "$ROOT_DIR"

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
STATUS="PASS"

{
  echo "# Waqfa Bootstrap Report"
  echo
  echo "**Date:** $(date --iso-8601=seconds)"
  echo "**Branch:** $BRANCH"
  echo "**Commit:** $COMMIT"
  echo "**Generated By:** tools/bootstrap/bootstrap.sh"
  echo "**Status:** pending"
  echo
  echo "## Environment"
  echo
  echo '```text'
  echo "Node: $(node --version 2>/dev/null || echo missing)"
  echo "pnpm: $(pnpm --version 2>/dev/null || echo missing)"
  echo "Docker: $(docker --version 2>/dev/null || echo missing)"
  echo '```'
  echo
  echo "## Actions"
  echo
} > "$REPORT"

if ! command -v node >/dev/null 2>&1; then
  echo "- FAIL: Node.js is not installed." >> "$REPORT"
  STATUS="FAIL"
fi

if ! command -v pnpm >/dev/null 2>&1; then
  echo "- FAIL: pnpm is not installed." >> "$REPORT"
  STATUS="FAIL"
fi

if [[ "$STATUS" == "PASS" ]]; then
  echo "- Running pnpm install --frozen-lockfile=false" >> "$REPORT"
  if ! pnpm install --frozen-lockfile=false >> "$REPORT" 2>&1; then
    STATUS="FAIL"
  fi
fi

sed -i "s/\*\*Status:\*\* pending/**Status:** $STATUS/" "$REPORT"
echo
echo "Bootstrap report: $REPORT"

[[ "$STATUS" == "PASS" ]]
