#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="$ROOT_DIR/00_Documentation/09_Reports/runtime"
TIMESTAMP="$(date +%F-%H%M%S)"
REPORT="$REPORT_DIR/${TIMESTAMP}-development-runtime-verification.md"

mkdir -p "$REPORT_DIR"
cd "$ROOT_DIR"

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
STATUS="PASS"

run_check() {
  local label="$1"
  shift
  echo "### $label" >> "$REPORT"
  echo >> "$REPORT"
  echo '```text' >> "$REPORT"
  if "$@" >> "$REPORT" 2>&1; then
    echo '```' >> "$REPORT"
    echo >> "$REPORT"
    echo "Result: PASS" >> "$REPORT"
  else
    local code=$?
    echo '```' >> "$REPORT"
    echo >> "$REPORT"
    echo "Result: FAIL (exit $code)" >> "$REPORT"
    STATUS="FAIL"
  fi
  echo >> "$REPORT"
}

{
  echo "# Waqfa Development Runtime Verification"
  echo
  echo "**Date:** $(date --iso-8601=seconds)"
  echo "**Branch:** $BRANCH"
  echo "**Commit:** $COMMIT"
  echo "**Generated By:** tools/bootstrap/verify.sh"
  echo "**Status:** pending"
  echo
  echo "## Checks"
  echo
} > "$REPORT"

run_check "Node.js" node --version
run_check "pnpm" pnpm --version
run_check "Workspace install state" pnpm install --frozen-lockfile
run_check "TypeScript typecheck" pnpm typecheck
run_check "Workspace build" pnpm build
run_check "Docker Compose configuration" docker compose -f infrastructure/compose/compose.development.yaml config

sed -i "s/\*\*Status:\*\* pending/**Status:** $STATUS/" "$REPORT"
echo "Verification report: $REPORT"

[[ "$STATUS" == "PASS" ]]
